spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      driver-class-name: ENC(XbJaB5lDMrdxnE/rR0MUPQvpNUUnY8awx2DHAKKPBwjPQdXCuIcP1Uad/xJUQh7h)
      jdbc-url: ENC(uoLfb9E0hRTwftxkJCEIoZ44ijO4Rks6Up0kVwRFoyUcNnHuAA/BHkFCny03VlnySJBBu3WkY5wg3zTNlGs8pQ==)
      username: ENC(r3equqi5pBtPNzBr9bM9oD5NtKQTCEXf)
      password: ENC(AxoIEnkkPzj3KTbi7umU1luUHntMsDHH)
  application:
    name: ShoppingMallBoot

  mvc:
    view:
      prefix: /html/
      suffix: .html
config:
  product-display-count: 12
  product-page-num-size: 5
  display-count: 100
  page-num-size: 5
logging:
  level:
    root: DEBUG

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )